// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ScanEventWorker.Data;

#nullable disable

namespace ScanEventWorker.Migrations
{
    [DbContext(typeof(ScanDbContext))]
    partial class ScanDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ParcelState", b =>
                {
                    b.Property<long>("ParcelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("ParcelId"));

                    b.Property<DateTime>("CreatedDateTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeliveryTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("LastEventId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("PickupTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("RunId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ParcelId");

                    b.ToTable("Parcels");
                });

            modelBuilder.Entity("WorkerState", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<long>("LastProcessedEventId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.ToTable("WorkerStates");
                });
#pragma warning restore 612, 618
        }
    }
}
